name: Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Juriba.DPC/**'

jobs:
  scriptanalyzer:
    runs-on: ubuntu-latest
    name: 'PowerShell Script Analyzer'
    steps:
      - uses: actions/checkout@v5
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: Juriba.DPC
          recurse: true
          includeDefaultRules: true
          enableExit: true
          excludeRules: PSAvoidTrailingWhitespace
